[package]
name = "simplified-aau-report"
version = "0.1.0"
entrypoint = "lib.typ"
authors = [""]
license = "MIT"
description = "A report template for students at Aalborg University (AAU)"
repository = ""
keywords = []
categories = []
compiler = "0.13.0"
exclude = ["fonts", "template/main.pdf"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
